src/modules/MUSeo/templates/metatag/main.tpl: config/templates/MUSeo/metatag/main.tpl
src/modules/MUSeo/templates/metatag/view.tpl: config/templates/MUSeo/metatag/view.tpl
src/modules/MUSeo/templates/metatag/view_quickNav.tpl: config/templates/MUSeo/metatag/view_quickNav.tpl
src/modules/MUSeo/templates/metatag/view.rss.tpl: config/templates/MUSeo/metatag/view.rss.tpl
src/modules/MUSeo/templates/metatag/display.tpl: config/templates/MUSeo/metatag/display.tpl
src/modules/MUSeo/templates/metatag/delete.tpl: config/templates/MUSeo/metatag/delete.tpl
src/modules/MUSeo/templates/metatag/include_displayItemListOne.tpl: config/templates/MUSeo/metatag/include_displayItemListOne.tpl
src/modules/MUSeo/templates/metatag/include_displayItemListMany.tpl: config/templates/MUSeo/metatag/include_displayItemListMany.tpl
src/modules/MUSeo/templates/extension/main.tpl: config/templates/MUSeo/extension/main.tpl
src/modules/MUSeo/templates/extension/view.tpl: config/templates/MUSeo/extension/view.tpl
src/modules/MUSeo/templates/extension/view_quickNav.tpl: config/templates/MUSeo/extension/view_quickNav.tpl
src/modules/MUSeo/templates/extension/view.rss.tpl: config/templates/MUSeo/extension/view.rss.tpl
src/modules/MUSeo/templates/extension/delete.tpl: config/templates/MUSeo/extension/delete.tpl
src/modules/MUSeo/templates/admin/header.tpl: config/templates/MUSeo/admin/header.tpl
src/modules/MUSeo/templates/admin/footer.tpl: config/templates/MUSeo/admin/footer.tpl
src/modules/MUSeo/templates/user/header.tpl: config/templates/MUSeo/user/header.tpl
src/modules/MUSeo/templates/user/footer.tpl: config/templates/MUSeo/user/footer.tpl
src/modules/MUSeo/templates/admin/inlineRedirectHandler.tpl: config/templates/MUSeo/admin/inlineRedirectHandler.tpl
src/modules/MUSeo/templates/user/inlineRedirectHandler.tpl: config/templates/MUSeo/user/inlineRedirectHandler.tpl
src/modules/MUSeo/templates/metatag/edit.tpl: config/templates/MUSeo/metatag/edit.tpl
src/modules/MUSeo/templates/metatag/inlineRedirectHandler.tpl: config/templates/MUSeo/metatag/inlineRedirectHandler.tpl
src/modules/MUSeo/templates/extension/edit.tpl: config/templates/MUSeo/extension/edit.tpl
src/modules/MUSeo/templates/extension/inlineRedirectHandler.tpl: config/templates/MUSeo/extension/inlineRedirectHandler.tpl
src/modules/MUSeo/templates/helper/include_standardfields_display.tpl: config/templates/MUSeo/helper/include_standardfields_display.tpl
src/modules/MUSeo/templates/helper/include_standardfields_edit.tpl: config/templates/MUSeo/helper/include_standardfields_edit.tpl
src/modules/MUSeo/templates/admin/config.tpl: config/templates/MUSeo/admin/config.tpl
src/modules/MUSeo/templates/include_pdfheader.tpl: config/templates/MUSeo/include_pdfheader.tpl
